const coffeeData = [
    {
        name: "Honey Lavender Latte",
        img: "https://theboozyginger.com/wp-content/uploads/2021/01/Honey-Lavender-Latte-7-scaled.jpg",
        milk: "steamed milk",
        flavors: "2 pump(s) lavender syrup + honey",
        espresso: "2 shots",
        toppings: "lavender flower garnish",
        price: "$4.50",
    },
    {
        name: "House Cold Brew",
        img: "https://fitfoodiefinds.com/wp-content/uploads/2021/05/Sweet-Cream-Cold-Brew-16-650x975.jpg",
        milk: "whole milk",
        flavors: "3 tbsp vanilla creamer",
        espresso: "none",
        toppings: "none",
        price: "$5",
        
    },
    {
        name: "House Made Vanilla Latte",
        img: "https://www.tasteslovely.com/wp-content/uploads/2017/06/Whole30-Vanilla-Latte-Coffee-a-dairy-free-refined-sugar-free-Whole30-approved-and-paleo-vanilla-latte-that-is-better-than-Starbucks-1-683x1024.jpg",
        milk: "steamed milk",
        flavors: "3 pump(s) vanilla syrup",
        espresso: "2 shots",
        toppings: "vanilla flower garnish",
        price: "$3.50",
    },
    {
        name: "Hazelnut Mocha",
        img: "https://thissillygirlskitchen.com/wp-content/uploads/2022/03/white-chocolate-mocha-frappuccino-9.jpg",
        milk: "2% milk",
        flavors: "3 pump(s) hazelnut syrup",
        espresso: "2 shots",
        toppings: "hazelnut shavings",
        price: "$3.00",
    },
    {
        name: "Matcha Latte",
        img: "https://www.acozykitchen.com/wp-content/uploads/2017/04/IcedMatchaLatte-1-300x300.jpg",
        milk: "steamed milk",
        flavors: "3 scoop(s) matcha powder",
        espresso: "none",
        toppings: "honey drizzle",
        price: "$3.75",
    },
    {
        name: "Iced Caramel Macchiato",
        img: "https://images.immediate.co.uk/production/volatile/sites/30/2022/04/Iced-Caramel-Macchiato-f4a10f9.jpg?quality=90&webp=true&resize=300,272",
        milk: "steamed milk",
        flavors: "2 pump(s) vanilla syrup",
        espresso: "2 shots",
        toppings: "caramel drizzle",
        price: "$3.00",
    },
    {
        name: "Dirty Chai Latte",
        img: "https://boulderlocavore.com/wp-content/uploads/2020/10/Chai-Masala-and-latte-title-image-500x500.jpg",
        milk: "steamed milk",
        flavors: "2 pump(s) vanilla",
        espresso: "2 shots",
        toppings: "whip cream + cinnamon",
        price: "$3.00",
    },
    {
        name: "Homemade Hot Chocolate",
        img: "https://www.allrecipes.com/thmb/1D9VifIlr7wx87iF55R0k2h3x5E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20211-creamy-hot-cocoa-vat-hero-1x1-1-2000-65d5201be8cf4990a2db71c3e2f9d19c.jpg",
        milk: "steamed milk",
        flavors: "2 pump(s) vanilla",
        espresso: "2 shots",
        toppings: "whip cream + cinnamon",
        price: "$3.00",
    },
    {
        name: "Gingerbread latte",
        img: "https://www.thecookierookie.com/wp-content/uploads/2015/10/slow-cooker-gingerbread-latte-4-of-10-650x925.jpg",
        milk: "steamed milk",
        flavors: "2 pump(s) vanilla",
        espresso: "2 shots",
        toppings: "gingerbread man",
        price: "$4.50",
    },
];

module.exports = coffeeData;